/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2017-03-30 01:56:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.blog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("file:/E:/repository/Central_NEO/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar", Long.valueOf(1490665290425L));
    _jspx_dependants.put("jar:file:/E:/repository/Central_NEO/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1488328488000L));
    _jspx_dependants.put("file:/E:/repository/Central_NEO/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1479872003037L));
    _jspx_dependants.put("jar:file:/E:/repository/Central_NEO/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html class=\"no-js\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>Amaze UI Admin index Examples</title>\r\n");
      out.write("<meta name=\"description\" content=\"index é¡µé¢\">\r\n");
      out.write("<meta name=\"keywords\" content=\"index\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"../amazeui/assets/i/favicon.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\"\r\n");
      out.write("\thref=\"../amazeuiassets/i/app-icon72x72@2x.png\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-title\" content=\"Amaze UI\">\r\n");
      out.write("<script src=\"../amazeui/assets/js/echarts.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../amazeui/assets/css/amazeui.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"../amazeui/assets/css/amazeui.datatables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../amazeui/assets/css/app.css\">\r\n");
      out.write("<script src=\"../amazeui/assets/js/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body data-type=\"index\" class=\"theme-black\">\r\n");
      out.write("\t<script src=\"../amazeui/assets/js/theme.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"am-g tpl-g\">\r\n");
      out.write("\t\t<!-- å¤´é¨-->\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<!-- logo -->\r\n");
      out.write("\t\t\t<div class=\"am-fl tpl-header-logo\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:;\"><img src=\"../amazeui/assets/img/logo.png\"\r\n");
      out.write("\t\t\t\t\talt=\"\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- å·¦ä¾§åå®¹ -->\r\n");
      out.write("\t\t\t<div class=\"tpl-header-fluid\">\r\n");
      out.write("\t\t\t\t<!-- ä¾§è¾¹åæ¢ -->\r\n");
      out.write("\t\t\t\t<div class=\"am-fl tpl-header-switch-button am-icon-list\">\r\n");
      out.write("\t\t\t\t\t<span> </span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- æç´¢ -->\r\n");
      out.write("\t\t\t\t<div class=\"am-fl tpl-header-search\">\r\n");
      out.write("\t\t\t\t\t<form class=\"tpl-header-search-form\" action=\"javascript:;\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"tpl-header-search-btn am-icon-search\"></button>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"tpl-header-search-box\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"æç´¢åå®¹...\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- å¶å®åè½-->\r\n");
      out.write("\t\t\t\t<div class=\"am-fr tpl-header-navbar\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<!-- æ¬¢è¿è¯­ -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"am-text-sm tpl-header-navbar-welcome\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:;\">æ¬¢è¿ä½ , <span>Amaze UI</span>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- æ°é®ä»¶ -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"am-dropdown tpl-dropdown\" data-am-dropdown=\"\"></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- æ°æç¤º -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"am-dropdown\" data-am-dropdown=\"\"></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- éåº -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"am-text-sm\"><a href=\"javascript:;\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"am-icon-sign-out\"></span> éåº\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<!-- é£æ ¼åæ¢ -->\r\n");
      out.write("\t\t<div class=\"tpl-skiner\">\r\n");
      out.write("\t\t\t<div class=\"tpl-skiner-toggle am-icon-cog\"></div>\r\n");
      out.write("\t\t\t<div class=\"tpl-skiner-content\">\r\n");
      out.write("\t\t\t\t<div class=\"tpl-skiner-content-title\">éæ©ä¸»é¢</div>\r\n");
      out.write("\t\t\t\t<div class=\"tpl-skiner-content-bar\">\r\n");
      out.write("\t\t\t\t\t<span class=\"skiner-color skiner-white\" data-color=\"theme-white\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"skiner-color skiner-black\" data-color=\"theme-black\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- ä¾§è¾¹å¯¼èªæ  -->\r\n");
      out.write("\t\t<div class=\"left-sidebar\">\r\n");
      out.write("\t\t\t<!-- ç¨æ·ä¿¡æ¯ -->\r\n");
      out.write("\t\t\t<div class=\"tpl-sidebar-user-panel\">\r\n");
      out.write("\t\t\t\t<div class=\"tpl-user-panel-slide-toggleable\">\r\n");
      out.write("\t\t\t\t\t<div class=\"tpl-user-panel-profile-picture\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"../amazeui/assets/img/user04.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span class=\"user-panel-logged-in-text\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"am-icon-circle-o am-text-success tpl-user-panel-status-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\tç¦è¨å°å¼ \r\n");
      out.write("\t\t\t\t\t</span> <a href=\"javascript:;\" class=\"tpl-user-panel-action-link\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"am-icon-pencil\"></span> è´¦å·è®¾ç½®\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- èå -->\r\n");
      out.write("\t\t\t<ul class=\"sidebar-nav\">\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- åå®¹åºå -->\r\n");
      out.write("\t\t<div class=\"tpl-content-wrapper\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--[if (gte IE 9)|!(IE)]><!-->\r\n");
      out.write("\t<script src=\"../amazeui/assets/js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!--<![endif]-->\r\n");
      out.write("\t<!--[if lte IE 8 ]>\r\n");
      out.write("<script src=\"http://libs.baidu.com/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js\"></script>\r\n");
      out.write("<script src=\"assets/js/amazeui.ie8polyfill.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\t<script src=\"../amazeui/assets/js/amazeui.min.js\"></script>\r\n");
      out.write("\t<script src=\"../amazeui/assets/js/amazeui.datatables.min.js\"></script>\r\n");
      out.write("\t<script src=\"../amazeui/assets/js/dataTables.responsive.min.js\"></script>\r\n");
      out.write("\t<script src=\"../amazeui/assets/js/app.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
