server:
   port: 9092
   
spring:
   application: 
       name: eureka.consumer
    
eureka:
   client:
         registerWithEureka: false 
         serviceUrl:
             defaultZone: http://localhost:8761/eureka/
   instance:
         prefer-ip-address: true
   healthcheck:
      enabled: true
        
 