spring:
   application: 
       name: blog-service
   datasource:
       driverClassName: com.mysql.jdbc.Driver
       url: jdbc:mysql://172.20.20.100/blog?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
       username: root
       password: 123456
    
eureka:
   client:
         serviceUrl:
             defaultZone: http://peer1.xujin.org:8761/eureka/
   instance:
         appname: blog-service
         prefer-ip-address: true
         
       
mybatis:   
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.pong.blog.model
 
 
 
---
spring:
    profiles: service-01
server:
    port: 9090 

---
spring:
    profiles: service-02
server:
    port: 9091 
    
    
    
    
    