server:
   port: 9092

service:
    blog-url: http://blog-service/
    upload:
         path: e:\upload\file\
         url: /ue/file/
   
   
spring:
   application: 
       name: blog-management
   thymeleaf:
       mode: HTML5
       prefix: classpath:/templates/
       suffix: .html 
       encoding: UTF-8 
       content-type: text/html  
       cache: false
   http:
       encoding:
             force: true
             charset: utf-8
             enabled: true
   data:
       mongodb:
             host: mongo1.blog.com
             port: 27017
             database: blog
             uri: mongodb://mongo1.blog.com:27017/blog
eureka:
   client:
         registerWithEureka: false 
         serviceUrl:
             defaultZone: http://peer1.xujin.org:8761/eureka/
   instance:
         prefer-ip-address: true

        
 