project:
  artifactId: blog-management
  name: blog-management
  description: blog-management

# Server settings (ServerProperties)
server:
  port: 8081
  address: 127.0.0.1
  name: blog-management
  sessionTimeout: 30
  contextPath: /management

  # Tomcat specifics
  tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs

security:
  basic:
    enabled: false
  require_ssl: false
  ignored: 
    - /lib/**
    - /css/**
    - /font-custom/**
    - /img/**
    - /500
    - /404
    
spring:
  redis:
     host: 172.20.20.100
     port: 6379
     pool:
       max-idle: 8
       min-idle: 0
       max-active: 8 
       max-wait: -1  
  
  http:
      encoding:
          charset: UTF-8
          enabled: true
          force: true

management:
  address: 127.0.0.1
  shell:
     ssh: 
        enabled: true
        port : 2222
     auth: spring
     

    
    
