spring:
  application:
    name: blog-eureka
    
---
spring:
    profiles: eureka-01
server:
    port: 8761  
eureka:
    client:
        serviceUrl:
            defaultZone: http://peer1.xujin.org:8762/eureka/
    instance:
        hostname: peer2.xujin.org
       
       
---
spring:
    profiles: eureka-02
server:
    port: 8762  
eureka:
    client:
        serviceUrl:
             defaultZone: http://peer2.xujin.org:8761/eureka/
    instance:
        hostname: peer1.xujin.org
        
