project:
  artifactId: blog-app
  name: blog-app
  description: blog-app


    
mybatis:   
  mapperLocations: classpath*:mapper/*.xml  
  typeAliasesPackage: com.pong.blog.model

security:
  basic:
    enabled: false
  require_ssl: false
  ignored: 
    - /lib/**
    - /css/**
    - /font-custom/**
    - /img/**
    - /500
    - /404
    
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.20.20.100/blog?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
  redis:
     host: 172.20.20.100
     port: 6379
     pool:
       max-idle: 8
       min-idle: 0
       max-active: 8 
       max-wait: -1  

management:
  address: 127.0.0.1
  shell:
     ssh: 
        enabled: true
        port : 2222
     auth: spring
     

    
    
