spring:
   application: 
       name: blog.provider
   datasource:
       driverClassName: com.mysql.jdbc.Driver
       url: jdbc:mysql://172.20.17.80/blog?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
       username: root
       password: 123456
    
eureka:
   client:
         serviceUrl:
             defaultZone: http://localhost:8761/eureka/
   instance:
         appname: blog.provider
         prefer-ip-address: true
         
       
mybatis:   
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.pong.blog.model
 
 
 
---
spring:
    profiles: provider-01
server:
    port: 9090 

---
spring:
    profiles: provider-02
server:
    port: 9091 
    
    
    
    
    